import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

// In-app admin alerts generated by the ingestion platform (repeated failures,
// credential problems, zero-import anomalies, duplicate spikes, scheduler
// errors). Deduped per source+type while unread so a failing source doesn't
// flood the inbox.
export const adminNotificationsTable = pgTable("admin_notifications", {
  id: uuid("id").primaryKey().defaultRandom(),
  type: text("type").notNull(), // 'repeated_failures'|'auth_expired'|'feed_unavailable'|'quota_exhausted'|'duplicate_spike'|'zero_events'|'scheduler_failure'
  severity: text("severity").notNull().default("warning"), // 'info'|'warning'|'critical'
  title: text("title").notNull(),
  body: text("body"),
  sourceId: uuid("source_id"),
  readAt: timestamp("read_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type AdminNotification = typeof adminNotificationsTable.$inferSelect;
export type AdminNotificationInsert = typeof adminNotificationsTable.$inferInsert;
