import { boolean, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const applicationsTable = pgTable("applications", {
  id: uuid("id").primaryKey().defaultRandom(),
  submissionType: text("submission_type").notNull().default("business"),
  businessName: text("business_name").notNull(),
  contactName: text("contact_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  website: text("website"),
  instagram: text("instagram"),
  category: text("category").array().notNull(),
  neighborhood: text("neighborhood").notNull(),
  address: text("address").notNull(),
  package: text("package").notNull(),
  routeId: text("route_id"),
  offer: text("offer").notNull(),
  prizeSponsorship: text("prize_sponsorship"),
  nearMarta: boolean("near_marta"),
  nearBeltline: boolean("near_beltline"),
  notes: text("notes"),
  logoUrl: text("logo_url"),
  subtitle: text("subtitle"),
  about: text("about"),
  businessHours: text("business_hours"),
  upcomingEvents: text("upcoming_events"),
  featuredMenuItems: text("featured_menu_items"),
  eventDate: text("event_date"),
  eventTime: text("event_time"),
  eventVenue: text("event_venue"),
  eventCost: text("event_cost"),
  eventUrl: text("event_url"),
  promoContact: boolean("promo_contact"),
  promoContactMethod: text("promo_contact_method"),
  // ── Vendor submissions (submissionType = "vendor") ───────────────────────
  vendorType: text("vendor_type"),
  // ── Authoritative pricing (validated server-side against @workspace/pricing)
  addOns: text("add_ons").array(),
  listingPrice: integer("listing_price"),
  // ── CRM fields ────────────────────────────────────────────────────────────
  salesStage: text("sales_stage").notNull().default("new"),
  assignedTo: text("assigned_to"),
  lastContactAt: timestamp("last_contact_at", { withTimezone: true }),
  nextFollowUpAt: timestamp("next_follow_up_at", { withTimezone: true }),
  crmNotes: text("crm_notes"),
  paymentStatus: text("payment_status").notNull().default("unpaid"),
  emailDelivered: text("email_delivered").notNull().default("pending"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type Application = typeof applicationsTable.$inferSelect;
