import { boolean, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const legendsPostsTable = pgTable("legends_posts", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").unique(),
  title: text("title").notNull(),
  subtitle: text("subtitle"),
  excerpt: text("excerpt"),
  body: text("body"),
  category: text("category").notNull().default("guide"),
  tags: text("tags").array(),
  authorName: text("author_name"),
  authorBio: text("author_bio"),
  authorImage: text("author_image"),
  heroImage: text("hero_image"),
  galleryImages: text("gallery_images").array(),
  status: text("status").notNull().default("draft"),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  scheduledPublishAt: timestamp("scheduled_publish_at", { withTimezone: true }),
  isFeatured: boolean("is_featured").notNull().default(false),
  isHero: boolean("is_hero").notNull().default(false),
  readingTimeMinutes: integer("reading_time_minutes"),
  seoTitle: text("seo_title"),
  seoDescription: text("seo_description"),
  socialPreviewImage: text("social_preview_image"),
  relatedLocationSlugs: text("related_location_slugs").array(),
  relatedEventIds: text("related_event_ids").array(),
  relatedRouteSlugs: text("related_route_slugs").array(),
  relatedExperienceSlugs: text("related_experience_slugs").array(),
  viewCount: integer("view_count").notNull().default(0),
  adminNotes: text("admin_notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
