import { boolean, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const passportExperiencesTable = pgTable("passport_experiences", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").unique(),
  title: text("title").notNull(),
  subtitle: text("subtitle"),
  introduction: text("introduction"),
  heroImage: text("hero_image"),
  status: text("status").notNull().default("draft"),
  experienceType: text("experience_type").notNull().default("official"),
  durationMinutes: integer("duration_minutes"),
  distanceMiles: text("distance_miles"),
  difficulty: text("difficulty").notNull().default("moderate"),
  startingPointAddress: text("starting_point_address"),
  startingPointNeighborhood: text("starting_point_neighborhood"),
  walkingDirections: text("walking_directions"),
  drivingDirections: text("driving_directions"),
  martaDirections: text("marta_directions"),
  parkingNotes: text("parking_notes"),
  stampOpportunities: text("stamp_opportunities").array(),
  rewards: text("rewards"),
  isFeatured: boolean("is_featured").notNull().default(false),
  isSponsored: boolean("is_sponsored").notNull().default(false),
  isSeasonal: boolean("is_seasonal").notNull().default(false),
  isLimitedTime: boolean("is_limited_time").notNull().default(false),
  seasonalStartDate: text("seasonal_start_date"),
  seasonalEndDate: text("seasonal_end_date"),
  seoTitle: text("seo_title"),
  seoDescription: text("seo_description"),
  relatedEventIds: text("related_event_ids").array(),
  relatedLocationSlugs: text("related_location_slugs").array(),
  relatedRouteSlugs: text("related_route_slugs").array(),
  relatedPostSlugs: text("related_post_slugs").array(),
  adminNotes: text("admin_notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const experienceStopsTable = pgTable("experience_stops", {
  id: uuid("id").primaryKey().defaultRandom(),
  experienceId: text("experience_id").notNull(),
  orderIndex: integer("order_index").notNull().default(0),
  businessSlug: text("business_slug"),
  customName: text("custom_name"),
  customDescription: text("custom_description"),
  address: text("address"),
  neighborhood: text("neighborhood"),
  hasStamp: boolean("has_stamp").notNull().default(false),
  walkingDirectionsFromPrev: text("walking_directions_from_prev"),
  imageUrl: text("image_url"),
  durationMinutes: integer("duration_minutes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
